solver:
  time: 2.0
  delta time: 0.00002267573
probes:
  - type: magnet field
    size: [10, 10, 10]
    position: [0, 0, 0]
    divide: [4, 4, 4]
    output: ./output/magnet_field.csv
coils:
  - type: solenoide
    radius: 5.0 # mm
    wire resistance: 1.72e-11 # Î©*mm
    wire diameter: 0.6 #mm
    turns: 1000
    magnetic field strength: 1.3  # AlNiCo
    direction: [0, 1, 0]
    position: [0, 0, 0]
    height: 10 # mm
    extrude direction: positive
    output inductance: ./output/solenoid_inductance.csv
elements:
  - type: ferromagnet
    permeability: 5.0e-6  # H/mm
    input: ./input/displacement.csv
    output: ./output/ferromagnet.csv